language: go
sudo: required
services:
- docker
go:
- '1.11'
script:
- echo "Nchan Prometheus Exporter - commit:${TRAVIS_COMMIT}"
- make test
- make container VERSION=$TRAVIS_BRANCH
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then docker login -u $DOCKER_USERNAME
  -p $DOCKER_PASSWORD ; make push VERSION=$TRAVIS_BRANCH ; fi
env:
  global:
  - secure: O7IvznDFFygHf3rfpmM07d55BNA8yaDnI8IF5oxkpf8rPzFGyVm21be6qSIhTHsPZ7BsO1sEmjzx2suEmPtSSLTMyDWBPc4wjqzhXzluUb14cXRUiUD0Cdhhn2TlzRMfvm7WhJxLtBTDZD6jQ4KAKSziWKuK7gRuYYICysYkxbk+jgWhNrsqii+ZbgrFINZYs2nNUHUVHjfasvRH6uaHukmMUiTELBy012XAQUsHUILBTa8obyr/xgu6p5ecqmPZuAvoFKy6LjMwZJB6wjs0Iyt/2ftj1AoMk0rPQjUZaMHGScIn+ZI27nzB0h4iB+Bn/pr3Cq6Z2ouplON8W225N/Suzfv0kXmK1pUXLgO33flQJCWUd4efHL2Pk+aKki10mH9uV6TxKkeCQwaUP30vei5q7mVBDisWryGhfHY86G9j3D/EUByz1sEOby4koWBeiCcbMYAOctqYup6AWSbKeoHhNvyl/A2FXDMjGls+z6jNb1kd5jDvSCfNVn8JUUiZbl9i76J6VsEHtQkCgNM7juZUirswYM1Bdfq4ZOQUnBd/Z1NmcjNdRr4V8Zh0VjKkDd/a8ZCe7Ob2Ut08s+J7PyHN89TOPtvdB1sLlTcD96VlRLDl4GAOhAhz92+cmOSKZ3f7ugdqD97b3zThm+wIzeGVEqtu7adJlZHMr/mUr70=
  - secure: Pk4qQo3XnkDtuA/sTVIkV1M4WVIkKdeDwijWXUPjFHbcdHszTaiBS3LnEluh4BfC7InMcXYQk3RAhJzRglFk5zTbsfRnTqpEcuhNfxOBSQ0Kw1sMEiuLW02B36qleOCAp1Ud1aPicq4J+jT33f8EPgUKtT2f5/m1XqXPTagyB6GcY9GH6cZmfbmQl0IEJ2J4f065aU/5ptJXF9/FOowlfTaiNJBNhbwdNTqbHBP3DXCsnOPXCRoR3XBBwuNa/YyV2e6acDwlLjhqYDPwXkplUgkm3sLkllkubARrrExf7Flks7Ooj1Wb/R9OKAUId2S2extNVi+I3K5HUgxXn20elPxyNSXhLlIATBGB8AVUp3o+jmvuhuoOOlm8pSNMuvmI8BpLZESpDEbX5X3mmS8Gct/VXbFi6Hg8gOwC6YwmZHqFNDzz/k44NuD0eMIYpvIaqLjc5ujzQIRQLkJ2P7Xg8V0LtWuASesKDy+axf/CBjtQNjlFPgqkF8VdKXjQLw7BHQmLAaGwxm934rYei6T4qJYgcrcuBExaVZCiqP0hjScNR4G0/4fxqgw97kfbI5Z9Uwc9ILJzWMCeK9dUtUdtPloE0YjQeyZ2ywEHSzIVwtTS3t+MhDfmen6Q7sMPYD12Ya2pDsCLPM+Xzm93E+552UdFyJb61Gn6s/O71us1gjg=
